name: Deploy Conduktor Gateway

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy (e.g., dev, stg or prod)"
        required: true
        default: "dev"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Set Environment Variable
        id: set-env
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: environments/${{ env.ENVIRONMENT }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: environments/${{ env.ENVIRONMENT }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: environments/${{ env.ENVIRONMENT }}

      - name: Post Deployment Outputs
        run: terraform output
        working-directory: environments/${{ env.ENVIRONMENT }}
